language: ruby
# To use rbx environment.
dist: trusty
sudo: false
cache:
  - bundler
before_install:
  - gem update bundler
matrix:
  include:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.4
    - rvm: 2.4.1
    - rvm: 2.4.1
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - rvm: ruby-head
    - rvm: ruby-head
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - rvm: rbx-3
    - rvm: jruby
  allow_failures:
    #- rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby
  fast_finish: true
script:
  - RUBYOPT="$RUBYOPT $TEST_RUBYOPT" bundle exec rake
notifications:
  email:
    - test-unit-commit@googlegroups.com
