language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - rbx-2
  - jruby
before_install:
  - gem update bundler
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
notifications:
  email:
    - test-unit-commit@googlegroups.com
