language: ruby
# To use rbx environment.
dist: trusty
sudo: false
cache:
  - bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
  - ruby-head
  - rbx-3
  - jruby
before_install:
  - gem update bundler
matrix:
  allow_failures:
    #- rvm: ruby-head
    - rvm: rbx-3
    #- rvm: jruby
  fast_finish: true
notifications:
  email:
    - test-unit-commit@googlegroups.com
