version: "{build}"
clone_depth: 10

notifications:
  - provider: Email
    to:
      - test-unit-commit@googlegroups.com
    on_build_status_changed: true

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle install

build: off

test_script:
  - bundle exec rake
